import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { FileText, Download, Calendar, Plus } from "lucide-react";

export const ReportsView = () => {
  const reports = [
    {
      id: 1,
      title: "Progress Assessment Report",
      type: "Assessment",
      date: "2025-01-12",
      doctor: "Dr. Priya Sharma",
      status: "completed",
      size: "2.4 MB"
    },
    {
      id: 2,
      title: "Initial Consultation Report",
      type: "Consultation",
      date: "2025-01-10",
      doctor: "Dr. Priya Sharma",
      status: "completed",
      size: "1.8 MB"
    },
    {
      id: 3,
      title: "Dosha Analysis Report",
      type: "Analysis",
      date: "2025-01-08",
      doctor: "Dr. Raj Kumar",
      status: "completed",
      size: "3.1 MB"
    },
    {
      id: 4,
      title: "Mid-Treatment Evaluation",
      type: "Evaluation",
      date: "2025-01-15",
      doctor: "Dr. Priya Sharma",
      status: "pending",
      size: "TBD"
    }
  ];

  const getStatusColor = (status: string) => {
    switch (status) {
      case "completed":
        return "bg-wellness text-white";
      case "pending":
        return "bg-accent text-accent-foreground";
      case "in-progress":
        return "bg-primary text-primary-foreground";
      default:
        return "bg-secondary text-secondary-foreground";
    }
  };

  const getTypeIcon = (type: string) => {
    return <FileText className="w-4 h-4" />;
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold text-primary mb-2">My Reports</h1>
          <p className="text-muted-foreground">Download and view your medical reports</p>
        </div>
        <Button className="bg-primary hover:bg-primary/90">
          <Plus className="w-4 h-4 mr-2" />
          Request New Report
        </Button>
      </div>

      {/* Reports List */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center text-primary">
            <FileText className="w-5 h-5 mr-2" />
            Available Reports
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="space-y-4">
            {reports.map((report) => (
              <div
                key={report.id}
                className="flex items-center justify-between p-4 bg-card rounded-lg border border-border hover:shadow-sm transition-shadow"
              >
                <div className="flex items-center space-x-4">
                  <div className="w-10 h-10 bg-wellness-light/20 rounded-lg flex items-center justify-center">
                    {getTypeIcon(report.type)}
                  </div>
                  <div className="flex-1">
                    <div className="flex items-center space-x-3 mb-1">
                      <h3 className="font-semibold text-foreground">{report.title}</h3>
                      <Badge className={getStatusColor(report.status)} variant="secondary">
                        {report.status}
                      </Badge>
                    </div>
                    <div className="flex items-center space-x-4 text-sm text-muted-foreground">
                      <div className="flex items-center">
                        <Calendar className="w-4 h-4 mr-1" />
                        {report.date}
                      </div>
                      <span>Type: {report.type}</span>
                      <span>Size: {report.size}</span>
                    </div>
                    <p className="text-sm text-muted-foreground mt-1">
                      Generated by {report.doctor}
                    </p>
                  </div>
                </div>
                <div className="flex items-center space-x-2">
                  {report.status === "completed" ? (
                    <>
                      <Button variant="outline" size="sm">
                        View
                      </Button>
                      <Button size="sm" className="bg-wellness hover:bg-wellness/90">
                        <Download className="w-4 h-4 mr-1" />
                        Download
                      </Button>
                    </>
                  ) : (
                    <Badge variant="secondary" className="bg-accent/20 text-accent">
                      In Progress
                    </Badge>
                  )}
                </div>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>

      {/* Report Categories */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <Card className="border-wellness-light/50 hover:shadow-md transition-shadow">
          <CardContent className="pt-6">
            <div className="flex items-center space-x-3">
              <div className="w-10 h-10 bg-wellness/10 rounded-lg flex items-center justify-center">
                <FileText className="w-5 h-5 text-wellness" />
              </div>
              <div>
                <h3 className="font-semibold text-primary">Assessment Reports</h3>
                <p className="text-sm text-muted-foreground">2 available</p>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card className="border-accent/50 hover:shadow-md transition-shadow">
          <CardContent className="pt-6">
            <div className="flex items-center space-x-3">
              <div className="w-10 h-10 bg-accent/10 rounded-lg flex items-center justify-center">
                <FileText className="w-5 h-5 text-accent" />
              </div>
              <div>
                <h3 className="font-semibold text-primary">Analysis Reports</h3>
                <p className="text-sm text-muted-foreground">1 available</p>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card className="border-primary/50 hover:shadow-md transition-shadow">
          <CardContent className="pt-6">
            <div className="flex items-center space-x-3">
              <div className="w-10 h-10 bg-primary/10 rounded-lg flex items-center justify-center">
                <FileText className="w-5 h-5 text-primary" />
              </div>
              <div>
                <h3 className="font-semibold text-primary">Consultation Reports</h3>
                <p className="text-sm text-muted-foreground">1 available</p>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
};